FROM mcr.microsoft.com/dotnet/sdk:5.0

COPY . /project

WORKDIR /project/src

# Setup dotnet and compile project to /calvin directory
RUN dotnet tool restore
RUN dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary --output /calvin

# Move playground to be easily accessible for binary file from its cwd
COPY ./src/static /calvin

EXPOSE 8085/tcp

CMD ["/calvin/calvin.service"]
